version: '3'
services:
  web:
    build: .
    image: "dzeniskajevic/antcol-internship-project:server_db"
    ports:
      - "3001:3001"
    environment:
      HOST: localhost
      DB_HOST: db
      database: newDb
      port: 27017:27017
  db:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: [ --auth ]
    volumes:
      - db-data:/data/db

volumes:
  db-data:
